### ISSUE TITLE
Support for dropwizard v0.8 series

### ISSUE THREAD

**Issue by carltonwhitehead** [federecio/dropwizard-swagger#30]
Are there any plans to support dropwizard's v0.8 series? It introduces some breaking API changes with many dependency version upgrades, so I'm guessing upgrading dropwizard-swagger might be non-trivial.

I tried following the instructions to add dropwizard-swagger to my dropwizard 0.8-rc2-snapshot project, but I received the following stack trace when I run my integration tests:
```
java.lang.NoClassDefFoundError: com/sun/jersey/spi/service/ServiceFinder
	at io.dropwizard.views.ViewBundle.<init>(ViewBundle.java:87)
	at io.federecio.dropwizard.swagger.SwaggerDropwizard.onInitialize(SwaggerDropwizard.java:40)
	at org.coner.ConerDropwizardApplication.initialize(ConerDropwizardApplication.java:56)
	at io.dropwizard.testing.DropwizardTestSupport.startIfRequired(DropwizardTestSupport.java:135)
	at io.dropwizard.testing.DropwizardTestSupport.before(DropwizardTestSupport.java:71)
	at io.dropwizard.testing.junit.DropwizardAppRule.before(DropwizardAppRule.java:66)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.ClassNotFoundException: com.sun.jersey.spi.service.ServiceFinder
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more
```
I cloned the [dropwizard-swagger-sample-app](https://github.com/federecio/dropwizard-swagger-sample-app), and it built and ran perfectly as-is, but when I upgraded its dropwizard dependency to v0.8.0-rc2-SNAPSHOT, I now receive essentially the same stack trace as seen in my project's integration tests:
```
$ java -jar target/dropwizard-swagger-sample-app-1.0-SNAPSHOT.jar server src/main/resources/sample-config.yaml 
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jersey/spi/service/ServiceFinder
	at io.dropwizard.views.ViewBundle.<init>(ViewBundle.java:87)
	at io.federecio.dropwizard.swagger.SwaggerDropwizard.onInitialize(SwaggerDropwizard.java:35)
	at io.federecio.dropwizard.swagger.sample.SampleApplication.initialize(SampleApplication.java:21)
	at io.dropwizard.Application.run(Application.java:71)
	at io.federecio.dropwizard.swagger.sample.SampleApplication.main(SampleApplication.java:16)
Caused by: java.lang.ClassNotFoundException: com.sun.jersey.spi.service.ServiceFinder
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
```

**Comment by carltonwhitehead** [comment]
I forked this repo, dropwizard-junit, and dropwizard-swagger-sample-app and updated each of them to use the current development snapshot of dropwizard-0.8. There were a few bumps along the way, but I got the basic cases demonstrated in the sample app working. However, in order to build a dropwizard-swagger artifact, I had to make an adjustment to the test that probably should not be accepted in a pull request. Also, the selenium tests are still failing.  See https://github.com/carltonwhitehead/dropwizard-swagger/commit/d8cac4e39244989c562f83a0c897e4c3dfe17952

**Comment by eric239** [comment]
Hi @carltonwhitehead 
Is there a way to work around the above exception trace? My project depends on dw 0.8 but I hoped to take advantage of swagger "auto-magically", sad to realize the magic is broken...

**Comment by jogura** [comment]
I ran into the same issue. You can get around this by including the dependency on the latest version of `dropwizard-views-freemarker`

For example, if you're using gradle you can modify the `build.gradle` file and include as a dependency:

`compile "io.dropwizard:dropwizard-views-freemarker:[your version of dw - 0.8.0X]"`

**Comment by alph486** [comment]
Is just including new latest freemarker enough, though? The original problem above has to do with classes declared in the dropwizard-views package. You'd need the latest of that to fix the problem, and when you get that imported you get this issue:

```
Exception in thread "main" java.lang.InstantiationError: io.dropwizard.views.ViewBundle
	at io.federecio.dropwizard.swagger.SwaggerDropwizard.onInitialize(SwaggerDropwizard.java:47)
	at com.actian.dataflood.service.DFApplication.initialize(DFApplication.java:51)
	at io.dropwizard.Application.run(Application.java:71)
	at com.actian.dataflood.service.DFApplication.main(DFApplication.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

because of the ViewBundle being abstract. If the ViewBundle were in a separate package you might be able to do dependency magic, but you need the latest views dependency. Fixes appear to be required to use this with 0.8.0.

On that note, mins ago on #37 @vultron81 submitted a pull request for this...

**Comment by federecio** [comment]
Dropwizard 0.8 is now supported in version 0.6 which has just been deployed to Maven Central and the README has been updated accordingly (@vultron81 and @thiagomoretto both submitted pull requests).
