### ISSUE TITLE
dropwizard-swagger doesn't work with dropwizard version 1.0.0

### ISSUE THREAD

**Issue by michaelruocco** [federecio/dropwizard-swagger#93]
I have noticed that there is an issue trying to use the dropwizard-swagger bundle (version 0.7.0) with dropwizard version 1.0.0. I was previously using 0.9.3 and it was working fine. The project I have been working with can be found here: https://github.com/michaelruocco/dropwizard-web-template.

When pulling this project and trying to run it locally after updating the build.gradle file to point at dropwizard version 1.0.0 for dropwizard-core, dropwizard-jdbi, dropwizard-testing, dropwizard-views-freemarker instead of version 0.9.3, I get the following error:

Exception in thread "main" java.lang.NoSuchMethodError: io.dropwizard.server.DefaultServerFactory.getJerseyRootPath()Ljava/lang/String;
    at io.federecio.dropwizard.swagger.ConfigurationHelper.getJerseyRootPath(ConfigurationHelper.java:53)
    at io.federecio.dropwizard.swagger.ConfigurationHelper.getSwaggerUriPath(ConfigurationHelper.java:84)
    at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:57)
    at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:37)
    at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
    at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
    at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
    at io.dropwizard.cli.Cli.run(Cli.java:75)
    at io.dropwizard.Application.run(Application.java:79)
    at uk.co.mruoc.Main.main(Main.java:7)

It seems that the io.dropwizard.server.DefaultServerFactory.getJerseyRootPath method has been modified and now returns an Optional<String> rather than just a String. I have forked the dropwizard-swagger repo and had a stab at fixing the issue (https://github.com/michaelruocco/dropwizard-swagger). I have resolved it an have all the tests passing, my only issue currently is that I had to turn of the maven enforcer plugin in order to get it to run as there were a lot of dependency clashes on the classpath after updating to dropwizard 1.0.0.

**Comment by jplock** [comment]
This project is no longer maintained.  I've been maintaining an updated copy at https://github.com/smoketurner/dropwizard-swagger

**Comment by michaelruocco** [comment]
Ah okay, I didn't realise! Thanks for letting me know.

**Comment by franco148** [comment]
Nice!!! it works great!!!! Thank you very much!!!

**Comment by KavithaRamm** [comment]
Thank you jplock, I have been breaking my head for the past 2 days. And I couldn't resolve the Exception.  Thanks for your post!!!

**Comment by Lvborderxlab** [comment]
thanks
